### ISSUE TITLE
Wrong null check resulting in possible exception

### ISSUE THREAD

**Issue by fly3rbug** [steelbreeze/state.cs#10]
InitialiseElements.cs at  line 43.
Incorrect null check

The line:
if (deepHistoryAbove || regionInitial != null || regionInitial.IsHistory)

has a check that checks to make sure that regionInitial is not NULL. However because of the OR semantics in the C# language the last statement regionInitial.IsHistory is also checked. On this point a null ref exception is raised because the IsHistory cannot be done on a NULL variable. 

In this case regionInitial is null. A better IF statement would be:
if (deepHistoryAbove || (regionInitial != null && regionInitial.IsHistory))

In this case, due to the C# semantics, the AND will first evaluate on the left side, find a false and then skip the right side evaluation. Therefor the regionInitial.IsHistory is not executed and does not raise a null ref exception. The IF would then go into the ELSE part of the IF.

**Comment by mesmo** [comment]
This was fixed in version 5.3.1 released 2016-03-02.

The line now reads:
if (deepHistoryAbove || regionInitial == null || regionInitial.IsHistory)

And was the original intent of the code: here we are determining of we should use history when entering a region. We use history semantics if:
* There was deep history defined in a parent region that was entered as part of this transition
* This region has deep or shallow history semantics
* There was no initial pseudo state defined (so we are seeing if there was a previously active state)
